# Verificação inicial da instalação do LDAP

- name: Obter informações sobre os pacotes já instalados
  package_facts:
    manager: auto

- name: Verificar se LDAP já está instalado
  block:
    - name: Mostrar mensagem de pacote já instalado
      debug:
        msg: "O pacote LDAP já está instalado."
      when: "'slapd ldap-utils' in ansible_facts.packages"

# Configuração inicial dos parametros do LDAP

- name: Configuração LDAP
  shell: |
    debconf-set-selections <<-EOF
    slapd slapd/internal/generated_adminpw password {{ ldap_user_pass }}
    slapd slapd/internal/adminpw password {{ ldap_user_pass }}
    slapd slapd/password2 password {{ ldap_user_pass }}
    slapd slapd/password1 password {{ ldap_user_pass }}
    slapd slapd/invalid_config boolean true
    slapd slapd/move_old_database boolean true
    slapd slapd/purge_database boolean false
    slapd slapd/no_configuration boolean false
    slapd slapd/domain string ufrgs.br
    slapd shared/organization string Universidade Federal do Rio Grande do Sul
    slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
    slapd slapd/dump_database select when needed
    EOF
    export DEBIAN_FRONTEND=noninteractive
  become: true
  become_user: root

# instalação do LDAP, caso ele não esteja instalado

- name: Instalar OpenLDAP
  package:
    name: 
      - slapd 
      - ldap-utils
    state: present
  when: "'slapd ldap-utils' not in ansible_facts.packages"
  become: true
  become_user: root


# Criação de diretórios

- name: Criar o diretório "ufrgs-openldap"
  file:
    path: /tmp
    state: directory
    owner: root
    group: root
  become: true
  become_user: root

- name: Criar o diretório "templates"
  file:
    path: /tmp/templates
    state: directory
    owner: root
    group: root
  become: true
  become_user: root

# Transferência dos arquivos da pasta "files" do "configure-openldap"

- copy:
    src: "{{ item }}"
    dest: /tmp/files_configuration/
    owner: root
    mode: 600
  with_fileglob:
    - "files/*"
    - "files/Indexes/*"
  become: true
  become_user: root

# Configuração do log próprio do ldap

- name: Verificar se o diretório "/var/log/slapd" já existe
  stat:
    path: /var/log/slapd
  register: stat_result_slapd_directory

- name: Criar o diretório "/var/log/slapd"
  file:
    path: /var/log/slapd
    state: directory
    owner: syslog
    group: adm
  when: not stat_result_slapd_directory
  become: true
  become_user: root

- name: Verificar se o arquivo "/var/log/slapd/ldap.log" já existe
  stat:
    path: /var/log/slapd/ldap.log
  register: stat_result_slapd_file

- name: Criar o arquivo "/var/log/slapd/ldap.log"
  file:
    path: /var/log/slapd
    state: touch
    owner: syslog
    group: adm
  when: not stat_result_slapd_file
  become: true
  become_user: root

- name: Movendo o arquivo "10-slapd.conf"
  command: mv /tmp/files_configuration/10-slapd.conf /etc/rsyslog.d/10-slapd.conf 
  become: true
  become_user: root

- name: Reiniciando o rsyslog
  command: systemctl restart rsyslog
  become: true
  become_user: root

- name: Movendo o arquivo "slapd"
  command: mv /tmp/files_configuration/slapd /etc/logrotate.d/slapd
  become: true
  become_user: root

- name: Reiniciando o logrotate
  command: systemctl restart logrotate
  become: true
  become_user: root


# Templates nos arquivos do "configure-openldap"

- name: Gerar arquivo "admin.ldif"
  ansible.builtin.template:
    src: templates/admin.ldif.j2
    dest: /tmp/templates/admin.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

- name: Gerar arquivo "replicator.ldif"
  ansible.builtin.template:
    src: templates/replicator.ldif.j2
    dest: /tmp/templates/replicator.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

- name: Gerar arquivo "replicator_config.ldif"
  ansible.builtin.template:
    src: templates/replicator_config.ldif.j2
    dest: /tmp/templates/replicator_config.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

# Adição dos arquivos dos templates do "configure-openldap"

- name: Importar o arquivo "admin.ldif"
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/templates/admin.ldif
  become: true
  become_user: root

- name: Verificar se o usuário "replicator" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,dc=teste' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'dc=teste' 'cn=replicator'
  register: ldap_replicator_check
  become: true
  become_user: root

- name: Importar o arquivo "replicator.ldif"
  command: ldapadd -x -D 'cn=admin,dc=teste' -w '{{ ldap_user_pass }}' -H ldapi:/// -f /tmp/templates/replicator.ldif
  when: ldap_replicator_check.stdout == ""
  become: true
  become_user: root

- name: Importar o arquivo "replicator_config.ldif"
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/templates/replicator_config.ldif"
  when: ldap_replicator_check.stdout == ""
  become: true
  become_user: root

  # Importar todos os schemas e arquivos padrões para o LDAP

- name: Importar arquivo "change_DbMaxSize.ldif" - altera o tamanho máximo da base
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/change-DbMaxSize.ldif
  become: true
  become_user: root

- name: Importar arquivo "change-LogLevel.ldif" - define nivel de log
  command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/change-LogLevel.ldif
  become: true
  become_user: root

- name: Verificar se o schema "misc" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -b 'cn=schema,cn=config' '(cn={*}misc)'
  register: ldap_misc_check
  become: true
  become_user: root

- name: Importar arquivo "misc.ldif" - importa o schema misc
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/misc.ldif"
  when: ldap_misc_check.stdout == ""
  become: true
  become_user: root

- name: Verificar se o schema "eduperson" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'cn=schema,cn=config' '(cn={*}eduperson)'
  register: ldap_eduperson_check
  become: true
  become_user: root

- name: Importar arquivo "schema-eduperson.ldif" - importa schema eduperson
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/schema-eduperson.ldif"
  when: ldap_eduperson_check.stdout == ""
  become: true
  become_user: root

- name: Verificar se o schema "authldap" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'cn=schema,cn=config' '(cn={*}authldap)'
  register: ldap_authldap_check
  become: true
  become_user: root

- name: Importar arquivo "schema-authldap.ldif" - importa schema authldap
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/schema-authldap.ldif"
  when: ldap_authldap_check.stdout == ""
  become: true
  become_user: root

- name: Verificar se o schema "samba" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'cn=schema,cn=config' '(cn={*}samba)'
  register: ldap_samba_check
  become: true
  become_user: root

- name: Importar arquivo "schema-samba.ldif" - importar schema samba
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/schema-samba.ldif"
  when: ldap_samba_check.stdout == ""
  become: true
  become_user: root
