# Criação do diretório "accesslog"

- name: Crie o diretório "accesslog"
  file:
    path: /var/lib/ldap/accesslog
    state: directory
    owner: openldap
    group: openldap
  become: true
  become_user: root

# Transferência de todos os arquivos da pasta "files" do "provider"

- copy:
    src: "{{ item }}"
    dest: /tmp/ufrgs-openldap/files_configuration/
    owner: root
    mode: 777
  with_fileglob:
    - "/home/eduardom/ansible/openldap/openldap2/openldap/ansible/roles/provider/files/*"
  become: true
  become_user: root

# Templates e adição dos arquivos da pasta "templates" do "provider"

- name: Adicionando o arquivo "provider_active_modules.ldif"
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ufrgs-openldap/files_configuration/provider-active-modules.ldif"
  become: true
  become_user: root

- name: Dar template no arquivo "new_database.ldif"
  ansible.builtin.template:
    src: /home/eduardom/ansible/openldap/ansible/roles/provider/templates/new_database.ldif.j2
    dest: /tmp/ufrgs-openldap/templates/new_database.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

- name: Adicionar new_database.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ufrgs-openldap/templates/new_database.ldif"
  become: true
  become_user: root

- name: Dar template no arquivo "overlay_sync.ldif"
  ansible.builtin.template:
    src: /home/eduardom/ansible/openldap/ansible/roles/provider/templates/overlay_sync.ldif.j2
    dest: /tmp/ufrgs-openldap/templates/overlay_sync.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root


- name: Adicionar overlay_sync.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ufrgs-openldap/templates/overlay_sync.ldif"
  become: true
  become_user: root

- name: Dar template no arquivo "overlay_accesslog.ldif"
  ansible.builtin.template:
    src: /home/eduardom/ansible/openldap/ansible/roles/provider/templates/overlay_accesslog.ldif.j2
    dest: /tmp/ufrgs-openldap/templates/overlay_accesslog.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

- name: Adicionar overlay_accesslog.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ufrgs-openldap/templates/overlay_accesslog.ldif"
  become: true
  become_user: root

- name: Dar template no arquivo "overlay_sync_accesslog.ldif"
  ansible.builtin.template:
    src: /home/eduardom/ansible/openldap/ansible/roles/provider/templates/overlay_sync_accesslog.ldif.j2
    dest: /tmp/ufrgs-openldap/templates/overlay_sync_accesslog.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root


- name: Adicionar overlay_sync_accesslog.ldif
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ufrgs-openldap/templates/overlay_sync_accesslog.ldif"
  become: true
  become_user: root

  # Excluir pasta-mãe dos arquivos de instalação LDAP

- name: Remover pasta-mãe dos arquivos de instalação LDAP
  ansible.builtin.file:
    path: /tmp/ufrgs-openldap
    state: absent
  become: true
  become_user: root

