# Template dos arquivos do "consumer"

- name: Dar template no arquivo "consumer.ldif"
  ansible.builtin.template:
    src: templates/consumer.ldif.j2
    dest: /tmp/templates/consumer.ldif
    owner: root
    group: wheel
    mode: '0644'
  become: true
  become_user: root

# Adição dos arquivos do consumer

- name: Verificar se a configuração de "módulos" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'cn=config' '(cn=module{1})' 
  register: ldap_modules_check
  become: true
  become_user: root

- name: Importar o arquivo "provider_active_modules.ldif" - habilita os módulos
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/files_configuration/provider-active-modules.ldif"
  when: ldap_modules_check.stdout == ""
  become: true
  become_user: root

- name: Verificar se a configuração de "consumer.ldif" já existe
  command: ldapsearch -x -LLL -D 'cn=admin,cn=config' -w '{{ ldap_user_pass }}' -H ldapi:/// -b 'olcDatabase={1}mdb,cn=config' '(olcSyncrepl=*)' 
  register: ldap_consumer_check
  become: true
  become_user: root

- name: Importar o arquivo "consumer.ldif"
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/templates/consumer.ldif
  when: ldap_consumer_check.stdout == ""
  become: true
  become_user: root
