- hosts: provider
  vars:
    suffix: dc=teste

  roles:
    - configure-openldap
    - provider

  vars_prompt:
    - name: "ldap_user_pass"
      prompt: "Digite a senha do usuário LDAP"
      private: yes
    - name: "ldap_admin_pass"
      prompt: "Digite a senha do usuário admin"
      private: yes
    - name: "replicator_pass"
      prompt: "Digite a senha do usuário replicator"
      private: yes
