- hosts: LDAP
  vars:
   slapd_root_password: "123"
  tasks:
   - name: Configurar senha do admin
     debconf:
       name: slapd/root_password
       question: slapd/root_password
       value: "{{ slapd_root_password | quote }}"
       vtype: password
     become: true
     become_user: root


   - name: Criar arquivos vazios
     file:
       path: "{{ item }}"
       state: touch
     loop:
       - /home/eduardom/ansible_provider/admin.ldif
       - /home/eduardom/ansible_provider/module.ldif
       - /home/eduardom/ansible_provider/replicator.ldif
       - /home/eduardom/ansible_provider/new_database.ldif
       - /home/eduardom/ansible_provider/index_sync.ldif
       - /home/eduardom/ansible_provider/overlay_sync.ldif
       - /home/eduardom/ansible_provider/overlay_accesslog.ldif
       - /home/eduardom/ansible_provider/overlay_sync_accesslog.ldif
       - /home/eduardom/ansible_provider/replicator_config.ldif
       - /home/eduardom/ansible_provider/replicator_config2.ldif
     become: true
     become_user: root


   - name: Crie o diretório accesslog
     file:
       path: /var/lib/ldap/accesslog
       state: directory
       owner: openldap
       group: openldap
     become: true


   - name: Escrever conteúdo LDIF em admin.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/admin.ldif
       block: |
         dn: olcDatabase={0}config,cn=config
         changetype: modify
         replace: olcRootPW
         olcRootPW: {SSHA}72DBbsejSDQg2GPWzDMf48Pbn+KINQac
     become: true
     become_user: root


   - name: Adicionar admin.ldif
     command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/admin.ldif
     become: true
     become_user: root


   - name: Escrevendo no replicator.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/replicator.ldif
       block: |
         dn: cn=replicator,dc=dev,dc=ufrgs,dc=br
         objectClass: simpleSecurityObject
         objectClass: organizationalRole
         cn: replicator
         description: Replication user
         userPassword: {SSHA}y+9NPwwhxgI5I7tcF4OmAfPTnIao6xik
     become: true
     become_user: root
  
   - name: Adicionar replicator.ldif
     command: ldapadd -x -D 'cn=admin,dc=dev,dc=ufrgs,dc=br' -w '123' -H ldapi:/// -f /home/eduardom/ansible_provider/replicator.ldif
     become: true
     become_user: root


   - name: Escrever conteúdo LDIF em module.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/module.ldif
       block: |
         dn: cn=module,cn=config
         objectClass: olcModuleList
         cn: module
         olcModulePath: /usr/lib/ldap/
         olcModuleLoad: accesslog.la
         olcModuleLoad: syncprov.la

     become: true
     become_user: root


   - name: Adicionar module.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/module.ldif"
     become: true
     become_user: root


   - name: Escrevendo no arquivo new_database.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/new_database.ldif
       block: |
         dn: olcDatabase={2}mdb,cn=config
         objectClass: olcDatabaseConfig
         objectClass: olcMdbConfig
         olcDatabase: {2}mdb
         olcDbDirectory: /var/lib/ldap/accesslog
         olcSuffix: cn=accesslog
         olcRootDN: cn=admin,dc=dev,dc=ufrgs,dc=br
         olcDbIndex: default eq
         olcDbIndex: entryCSN,objectClass,reqEnd,reqResult,reqStart
         olcAccess: {0}to * by dn.exact="cn=replicator,dc=dev,dc=ufrgs,dc=br" read by * break
         olcLimits: dn.exact="cn=replicator,dc=dev,dc=ufrgs,dc=br"
           time.soft=unlimited time.hard=unlimited
           size.soft=unlimited size.hard=unlimited
     become: true
     become_user: root


   - name: Adicionando o new_database.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/new_database.ldif"
     become: true
     become_user: root

   - name: Escrevendo no arquivo index_sync.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/index_sync.ldif
       block: |
         dn: olcDatabase={1}mdb,cn=config
         changetype: modify
         add: olcDbIndex
         olcDbIndex: entryCSN eq
         -
         add: olcDbIndex
         olcDbIndex: entryUUID eq
     become: true
     become_user: root

   - name: Adicionando o arquivo index_sync.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/index_sync.ldif"
     become: true
     become_user: root
    
   - name: Escrevendo no arquivo overlay_sync.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/overlay_sync.ldif
       block: |
         dn: olcOverlay={1}syncprov,olcDatabase={1}mdb,cn=config
         objectClass: olcConfig
         objectClass: olcOverlayConfig
         objectClass: olcSyncProvConfig
         objectClass: top
         olcOverlay: {1}syncprov
         olcSpCheckpoint: 20 5
     become: true
     become_user: root

   - name: Adicionando o arquivo overlay_sync.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/overlay_sync.ldif"
     become: true
     become_user: root

   - name: Escrevendo no arquivo overlay_accesslog.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/overlay_accesslog.ldif
       block: |
         olcSuffix: cn=accesslog
         dn: olcOverlay={1}accesslog,olcDatabase={1}mdb,cn=config
         objectClass: olcAccessLogConfig
         objectClass: olcOverlayConfig
         olcAccessLogDB: cn=accesslog
         olcOverlay: {1}accesslog
         olcAccessLogOps: writes
         olcAccessLogPurge: 07+00:00 01+00:00
         olcAccessLogSuccess: TRUE
     become: true
     become_user: root
        


   - name: Adicionando o arquivo overlay_accesslog.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/overlay_accesslog.ldif"
     become: true
     become_user: root


   - name: Escrevendo no arquivo overlay_sync_accesslog.ldif
     blockinfile:
       dest: /home/eduardom/ansible_provider/overlay_sync_accesslog.ldif
       block: |
         olcSuffix: cn=accesslog
         dn: olcOverlay={0}syncprov,olcDatabase={2}mdb,cn=config
         objectClass: olcConfig
         objectClass: olcOverlayConfig
         objectClass: olcSyncProvConfig
         objectClass: top
         olcOverlay: {0}syncprov
         olcSpNoPresent: TRUE
         olcSpReloadHint: TRUE
     become: true
     become_user: root


   - name: Adicionando o arquivo overlay_sync_accesslog.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/overlay_sync_accesslog.ldif"
     become: true
     become_user: root

   - name: Escrevendo no arquivo replicator_config.ldif
     blockinfile:
       dest: /home/eduardom/replicator_config.ldif
       block: |
         dn: olcDatabase={1}mdb,cn=config
         changetype: modify
         add: olcAccess
         olcAccess: {3}to * by dn="cn=replicator,dc=dev,dc=ufrgs,dc=br" write
     become: true
     become_user: root
        



   - name: Adicionando o arquivo replicator_config.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/replicator_config.ldif"
     become: true
     become_user: root

   - name: Escrevendo no arquivo replicator_config2.ldif
     blockinfile:
       dest: /home/eduardom/replicator_config2.ldif
       block: |
         dn: olcDatabase={1}mdb,cn=config
         changetype: modify
         add: olcAccess
         olcAccess: {0}to *
           by dn.exact="cn=replicator,dc=dev,dc=ufrgs,dc=br" read
           by * break
         -
         add: olcLimits
         olcLimits: dn.exact="cn=replicator,dc=dev,dc=ufrgs,dc=br"
           time.soft=unlimited time.hard=unlimited
           size.soft=unlimited size.hard=unlimited
     become: true
     become_user: root

   - name: Adicionando o arquivo replicator_config2.ldif
     shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /home/eduardom/ansible_provider/replicator_config2.ldif"
     become: true
     become_user: root









